### ISSUE TITLE
Backbone & PUT requests

### ISSUE THREAD

**Issue by lifeofcoding** [alixaxel/ArrestDB#15]
First off I absolutely love this. I haven't been able to find anything like it, says so much time making my backend api. with backbone my put request are being sent perfectly fine, though I keep getting conflict error. Other methods works fine with the backbone models, but saving a model that updates the backend, it where it goes wrong, the query string for mysql has all the data but my values, just abunch of question marks. (Do these get replaced before executing the query)

**Comment by jamespsterling** [comment]
I'm having this problem as well using angularjs. It's just doing a PUT with a json object. How did you resolve this?
