### ISSUE TITLE
Bad request with postgresql

### ISSUE THREAD

**Issue by nspassov** [alixaxel/ArrestDB#20]
Hi,

I am trying to hook ArrestDB to postgresql 9.1. I put the correct DSN and have the rewriting set up, but when doing any requests I get error 400. What could be wrong?

**Comment by rsgone** [comment]
Hi,

I am getting same error.

My DSN variable is  $dsn = 'pgsql://postgres:12345@localhost:5432/crmdb/';

And I am trying to access data like this http://52.17.102.17/api/tokens

I am getting following error :
{
    "error": {
        "code": 400,
        "status": "Bad Request"
    }
}

Thanks in advance.
R.S.Gone
