### ISSUE TITLE
POST return ID of newly created record?

### ISSUE THREAD

**Issue by captainclam** [alixaxel/ArrestDB#22]
Currently a successful POST is returning: `{success: {code: 201, status: "Created"}}`

Is it possible for the ID to be returned also, so I can use it right away?

I did this: https://github.com/captainclam/ArrestDB/commit/58ee661173804ceff57bfa2b13c56995a6e48a62

But not sure if it's a good idea, so have not submitted as a pull request. (disclaimer: totally untested on tables that do not have an id column or auto-increment id)

**Comment by ogizanagi** [comment]
It would be better to keep the `201`Response body empty, and add a `Location` header with the url of the newly created resource. (As described for example in http://williamdurand.fr/2012/08/02/rest-apis-with-symfony2-the-right-way/)

**Comment by gautiermichelin** [comment]
Anything back would be better than nothing at all. Even if the @ogizanagi seems more elegant.
Now, we're in full black when inserting. The fastest option(that I see) is to make a GET after, providing a discriminant value (playing with a timestamp).
