### ISSUE TITLE
503 - Service Unavailable

### ISSUE THREAD

**Issue by drveresh** [alixaxel/ArrestDB#41]
Hi,

Can you please help me resolve 503 Service Unavailable error when I hosted it a domain:
http://xyz.net/apps/ArrestDB/<tablename>/

None of these Sqlite Path didn't work in index.php:
$dsn = 'sqlite://./test.db'
$dsn = 'sqlite://./public_html/apps/ArrestDB/test.db.db'
$dsn = 'sqlite:///home/user/public_html/apps/ArrestDB/test.db.db'

Empty client: 
$clients = [];

All other files in that folder has full(755,777) permissions.

**Comment by assafmo** [comment]
Same problem here

**Comment by focussing** [comment]
what PHP version are you using?

**Comment by drveresh** [comment]
Using 5.5+ version.

**Comment by assafmo** [comment]
Me too

**Comment by focussing** [comment]
1) try with $dsn = 'sqlite://test.db'
when the test.db file and the index.php file are in the same directory
easy test

2) most probable:
https://stackoverflow.com/questions/8803728/pdo-sqlite-could-not-find-driver-php-file-not-processing
look what PHP version your server is running

**Comment by drveresh** [comment]
The test.db file is in same folder along with index.php, but with your option(sqlite://test.db), the complete service/app is down or broken, the webpage shows blank or disconnected page.

I tried again with "sqlite://./test.db", now got the page, but the service is broken with below error message:

{
    "error": {
        "code": 503,
        "status": "Service Unavailable"
    }
}

The exact version of PHP is 5.6.30.

**Comment by drveresh** [comment]
Finally, got resolved.  

For SQLite, I had to force write the mod_rewrite rules in the .htaccess file to get it fixed.  For MySQL, it worked without mod_rewrite.

For both issues, I had to access the URLs in the format "/index.php/<TABLE>/.." to get them working.
